blueprint:
  name: Trash Reminder via Calendar with Event Name as Trash Type
  description: >
    Sends trash day reminders at 10:00, 16:00, and 22:00 if any event is found in your trash calendar for tomorrow.
    Uses the event's name as the trash type.
    On the first notification, a todo item is added (via the Local Todo integration) with an ID in the format "EVENT_NAME-YYYY-MM-DD".
    The notification includes an action to mark the todo as done, preventing duplicate reminders.
    Can be triggered manually from the automation UI for testing.
  domain: automation
  input:
    calendar_entity:
      name: Trash Calendar
      description: "Calendar entity containing your trash day events."
      selector:
        entity:
          domain: calendar
    devices:
      name: Devices to Notify
      description: "Select mobile devices to receive notifications."
      selector:
        device:
          filter:
            integration: mobile_app
          multiple: true

trigger:
  - platform: time
    at: "10:00:00"
  - platform: time
    at: "16:00:00"
  - platform: time
    at: "22:00:00"
  - platform: event
    event_type: mobile_app_notification_action

variables:
  tomorrow: "{{ (now() + timedelta(days=1)).date() }}"
  tomorrow_str: "{{ (now() + timedelta(days=1)).strftime('%Y-%m-%d') }}"
  event_summary: "{{ state_attr(calendar_entity, 'message') | default('') }}"
  task_id: "{{ event_summary }}-{{ tomorrow_str }}"

action:
  - service: todo.add
    data:
      task: "{{ task_id }}"
      title: "Trash Reminder"
      message: "Don't forget to take out the {{ event_summary }} bin for tomorrow."
  - service: persistent_notification.create
    data:
      notification_id: "{{ task_id }}"
      title: "Trash day!"
      message: "Don't forget to take out the {{ event_summary }} bin for tomorrow.\n\nClick **Mark Done** when finished."
      data:
        actions:
          - action: "mark_done"
            title: "Mark Done"
        icon: mdi:trash-can
  - repeat:
      for_each: !input devices
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "Trash day!"
            message: "Don't forget to take out the {{ event_summary }} bin for tomorrow."
            data:
              actions:
                - action: "mark_done"
                  title: "Mark Done"
              icon: mdi:trash-can

mode: single
